---

 - name: Ensure apache is installed
   apt: name={{ item }} state=present
   with_items: "{{ apache_packages }}"

 - name: Enable apache modules
   apache2_module:
     state: present
     name: "{{ item }}"
   with_items: "{{ apache_mods_enabled }}"
   notify: restart apache2

 - name: Copy config file for nextcloud
   template:
     src: "{{ apache_nc_template  }}"
     dest: "{{ apache_conf_path }}/sites-available/{{ apache_nc_filename }}"
     owner: root
     group: root
     mode: 0644
   notify: restart apache2

 - name: Add nextcloud symlink in sites-enabled
   file: 
     src: "{{ apache_conf_path  }}/sites-available/{{ apache_nc_filename  }}"
     dest: "{{ apache_conf_path  }}/sites-enabled/{{ apache_nc_filename  }}"
     state: link
   notify: restart apache2

 - name: Remove default apache2 file
   file:
     path: "{{ apache_conf_path  }}/sites-enabled/000-default.conf"
     state: absent
   notify: restart apache2  
